version: "2.3"
services:
  app:
    build: .
    ports:
    - 8080:80
    environment:
      - MYSQL_HOST
      - MYSQL_USER
      - MYSQL_PASS
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASS}
    volumes:
      - ${PWD}/migrations:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    ports:
    - 8000:8080
    depends_on:
      - mysql